name: AgendaCloud-Menu
version: 1.0.2-SNAPSHOT
main: cat.kiwi.minecraft.metcdMenu.MEtcdMenuPlugin
load: STARTUP
authors: [ moeKiwiSAMA ]
description: AgendaCloud Menu
depends: [ MEtcd ]
api-version: 1.16
commands:
    am:
        description: Etcd register
        usage: /am <serverType>